parameters:
    dto.mapper.cache_dir: '%kernel.cache_dir%/dto-mapper'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DtoMapperBundle\Annotation\MappingMeta\:
      autowire: false
      resource: '../../Annotation/MappingMeta/*'

    DtoMapperBundle\Annotation\MappingMeta\NamingStrategy\:
      autowire: false
      resource: '../../Annotation/MappingMeta/NamingStrategy/*'

    DtoMapperBundle\Annotation\MappingMeta\Strategy\:
      autowire: false
      resource: '../../Annotation/MappingMeta/Strategy/*'

    DtoMapperBundle\Annotation\AnnotationReader:
      arguments:
        reader: '@Doctrine\Common\Annotations\Reader'

    DtoMapperBundle\Annotation\AnnotationReaderInterface:
      alias: DtoMapperBundle\Annotation\AnnotationReader

    DataMapper\MappingRegistry\ClassMappingRegistry:
    DataMapper\MappingRegistry\ClassMappingRegistryInterface:
      alias: DataMapper\MappingRegistry\ClassMappingRegistry

    DataMapper\MappingRegistry\NamingStrategyRegistry:
    DataMapper\MappingRegistry\NamingStrategyRegistryInterface:
      alias: DataMapper\MappingRegistry\NamingStrategyRegistry

    DataMapper\MappingRegistry\DestinationRegistry:
    DataMapper\MappingRegistry\DestinationRegistryInterface:
      alias: DataMapper\MappingRegistry\DestinationRegistry

    DataMapper\MappingRegistry\StrategyRegistry:
    DataMapper\MappingRegistry\StrategyRegistryInterface:
      alias: DataMapper\MappingRegistry\StrategyRegistry

    DataMapper\Hydrator\HydratorFactory:
    DataMapper\Hydrator\HydratorFactoryInterface:
      alias: DataMapper\Hydrator\HydratorFactory

    DataMapper\Mapper:
    DataMapper\MapperInterface:
      alias: DataMapper\Mapper

    DtoMapperBundle\Annotation\MappingMeta\NamingStrategy\SnakeCaseNamingStrategy:
    DtoMapperBundle\Annotation\MappingMeta\NamingStrategy\UnderscoreNamingStrategy:
    DtoMapperBundle\Annotation\MappingMeta\NamingStrategy\IdentityNamingStrategy:
#    DtoMapperBundle\Annotation\MappingMeta\NamingStrategy\:
#    DtoMapperBundle\Annotation\MappingMeta\Strategy\:
#    DataMapper\NamingStrategy\SnakeCaseNamingStrategy:
#    DataMapper\NamingStrategy\UnderscoreNamingStrategy:
#    DataMapper\NamingStrategy\IdentityNamingStrategy:

    DataMapper\MappingRegistry\MappingRegistry:
    DataMapper\MappingRegistry\MappingRegistryInterface:
      alias: DataMapper\MappingRegistry\MappingRegistry

    DataMapper\MappingRegistry\HydratorRegistry:
    DataMapper\MappingRegistry\HydratorRegistryInterface:
      alias: DataMapper\MappingRegistry\HydratorRegistry

    DataMapper\Hydrator\HydratedClassesFactory:
      arguments:
        targetDir: '%dto.mapper.cache_dir%'

    DtoMapperBundle\Hydrator\GeneratedHydratorCache:
      arguments:
        filesystem: '@Symfony\Component\Filesystem\Filesystem'
        hydratedClassesFactory: '@DataMapper\Hydrator\HydratedClassesFactory'
        cacheDir: '%dto.mapper.cache_dir%'

    DataMapper\Hydrator\ArrayCollectionHydrator:
    DataMapper\Hydrator\ArraySerializableHydrator:
    DataMapper\Hydrator\ObjectHydrator:
      shared: false
