parameters:
    dto.mapper.cache_dir: '%kernel.cache_dir%/dto-mapper'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DtoMapperBundle\Annotation\MappingMeta\:
      autowire: false
      resource: '../../Annotation/MappingMeta/*'

    DtoMapperBundle\Annotation\AnnotationReader:
      $reader: '@Doctrine\Common\Annotations\Reader'

    DtoMapperBundle\Annotation\AnnotationReaderInterface:
      alias: DtoMapperBundle\Annotation\AnnotationReader

    DataMapper\MappingRegistry\ClassMappingRegistry:
    DataMapper\MappingRegistry\ClassMappingRegistryInterface:
      alias: DataMapper\MappingRegistry\ClassMappingRegistry

    DataMapper\MappingRegistry\NamingStrategyRegistry:
    DataMapper\MappingRegistry\NamingStrategyRegistryInterface:
      alias: DataMapper\MappingRegistry\NamingStrategyRegistry

    DataMapper\MappingRegistry\DestinationRegistry:
    DataMapper\MappingRegistry\DestinationRegistryInterface:
      alias: DataMapper\MappingRegistry\DestinationRegistry

    DataMapper\MappingRegistry\StrategyRegistry:
    DataMapper\MappingRegistry\StrategyRegistryInterface:
      alias: DataMapper\MappingRegistry\StrategyRegistry

    DataMapper\Hydrator\HydratorFactory:
    DataMapper\Hydrator\HydratorFactoryInterface:
      alias: DataMapper\Hydrator\HydratorFactory

    DataMapper\Mapper:
    DataMapper\MapperInterface:
      alias: DataMapper\Mapper

    DtoMapperBundle\NamingStrategy\SnakeCaseNamingStrategy:
    DtoMapperBundle\NamingStrategy\UnderscoreNamingStrategy:
    DtoMapperBundle\NamingStrategy\IdentityNamingStrategy:

    DtoMapperBundle\MappingRegistry\MappingRegistry:
    DtoMapperBundle\MappingRegistry\MappingRegistryInterface:
      alias: DataMapper\MappingRegistry\MappingRegistry

    DtoMapperBundle\MappingRegistry\HydratorRegistry:
    DtoMapperBundle\MappingRegistry\HydratorRegistryInterface:
      alias: DataMapper\MappingRegistry\HydratorRegistry

    DtoMapperBundle\Hydrator\HydratedClassesFactory:
      arguments:
        $targetDir: '%dto.mapper.cache_dir%'

    DtoMapperBundle\Hydrator\GeneratedHydratorCache:
      arguments:
        $filesystem: '@Symfony\Component\Filesystem\Filesystem'
        $hydratedClassesFactory: '@DataMapper\Hydrator\HydratedClassesFactory'
        $cacheDir: '%dto.mapper.cache_dir%'

    DataMapper\Hydrator\ArrayCollectionHydrator:
    DataMapper\Hydrator\ArraySerializableHydrator:
    DataMapper\Hydrator\ObjectHydrator:
      shared: false
